/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedActivityRouteImport } from './routes/_authenticated/activity'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDocumentsRouteImport } from './routes/_authenticated/documents'
import { Route as AuthenticatedFocusRouteImport } from './routes/_authenticated/focus'
import { Route as AuthenticatedGoalsRouteImport } from './routes/_authenticated/goals'
import { Route as AuthenticatedHabitsRouteImport } from './routes/_authenticated/habits'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedPricingRouteImport } from './routes/_authenticated/pricing'
import { Route as AuthenticatedRoadmapsRouteImport } from './routes/_authenticated/roadmaps'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedStudyRouteImport } from './routes/_authenticated/study'
import { Route as AuthenticatedTasksRouteImport } from './routes/_authenticated/tasks'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiLogErrorRouteImport } from './routes/api/log-error'
import { Route as ApiMaterialChatRouteImport } from './routes/api/material-chat'
import { Route as ApiUploadDocumentRouteImport } from './routes/api/upload-document'
import { Route as AuthenticatedConversationIndexRouteImport } from './routes/_authenticated/conversation.index'
import { Route as AuthenticatedConversationThreadIdRouteImport } from './routes/_authenticated/conversation.$threadId'
import { Route as AuthenticatedLessonItemIdRouteImport } from './routes/_authenticated/lesson.$itemId'
import { Route as AuthenticatedMaterialResourceIdRouteImport } from './routes/_authenticated/material.$resourceId'
import { Route as AuthenticatedPagePageIdRouteImport } from './routes/_authenticated/page.$pageId'
import { Route as AuthenticatedResourceResourceIdRouteImport } from './routes/_authenticated/resource.$resourceId'
import { Route as AuthenticatedRoadmapRoadmapIdRouteImport } from './routes/_authenticated/roadmap.$roadmapId'
import { Route as ApiWebhooksRazorpayRouteImport } from './routes/api/webhooks/razorpay'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedActivityRoute = AuthenticatedActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDocumentsRoute = AuthenticatedDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFocusRoute = AuthenticatedFocusRouteImport.update({
  id: '/focus',
  path: '/focus',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGoalsRoute = AuthenticatedGoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHabitsRoute = AuthenticatedHabitsRouteImport.update({
  id: '/habits',
  path: '/habits',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPricingRoute = AuthenticatedPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRoadmapsRoute = AuthenticatedRoadmapsRouteImport.update({
  id: '/roadmaps',
  path: '/roadmaps',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStudyRoute = AuthenticatedStudyRouteImport.update({
  id: '/study',
  path: '/study',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTasksRoute = AuthenticatedTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLogErrorRoute = ApiLogErrorRouteImport.update({
  id: '/api/log-error',
  path: '/api/log-error',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMaterialChatRoute = ApiMaterialChatRouteImport.update({
  id: '/api/material-chat',
  path: '/api/material-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadDocumentRoute = ApiUploadDocumentRouteImport.update({
  id: '/api/upload-document',
  path: '/api/upload-document',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedConversationIndexRoute =
  AuthenticatedConversationIndexRouteImport.update({
    id: '/conversation/',
    path: '/conversation/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConversationThreadIdRoute =
  AuthenticatedConversationThreadIdRouteImport.update({
    id: '/conversation/$threadId',
    path: '/conversation/$threadId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLessonItemIdRoute =
  AuthenticatedLessonItemIdRouteImport.update({
    id: '/lesson/$itemId',
    path: '/lesson/$itemId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMaterialResourceIdRoute =
  AuthenticatedMaterialResourceIdRouteImport.update({
    id: '/material/$resourceId',
    path: '/material/$resourceId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPagePageIdRoute = AuthenticatedPagePageIdRouteImport.update({
  id: '/page/$pageId',
  path: '/page/$pageId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedResourceResourceIdRoute =
  AuthenticatedResourceResourceIdRouteImport.update({
    id: '/resource/$resourceId',
    path: '/resource/$resourceId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRoadmapRoadmapIdRoute =
  AuthenticatedRoadmapRoadmapIdRouteImport.update({
    id: '/roadmap/$roadmapId',
    path: '/roadmap/$roadmapId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiWebhooksRazorpayRoute = ApiWebhooksRazorpayRouteImport.update({
  id: '/api/webhooks/razorpay',
  path: '/api/webhooks/razorpay',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/focus': typeof AuthenticatedFocusRoute
  '/goals': typeof AuthenticatedGoalsRoute
  '/habits': typeof AuthenticatedHabitsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/pricing': typeof AuthenticatedPricingRoute
  '/roadmaps': typeof AuthenticatedRoadmapsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/study': typeof AuthenticatedStudyRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/api/chat': typeof ApiChatRoute
  '/api/health': typeof ApiHealthRoute
  '/api/log-error': typeof ApiLogErrorRoute
  '/api/material-chat': typeof ApiMaterialChatRoute
  '/api/upload-document': typeof ApiUploadDocumentRoute
  '/conversation/$threadId': typeof AuthenticatedConversationThreadIdRoute
  '/lesson/$itemId': typeof AuthenticatedLessonItemIdRoute
  '/material/$resourceId': typeof AuthenticatedMaterialResourceIdRoute
  '/page/$pageId': typeof AuthenticatedPagePageIdRoute
  '/resource/$resourceId': typeof AuthenticatedResourceResourceIdRoute
  '/roadmap/$roadmapId': typeof AuthenticatedRoadmapRoadmapIdRoute
  '/api/webhooks/razorpay': typeof ApiWebhooksRazorpayRoute
  '/conversation/': typeof AuthenticatedConversationIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/focus': typeof AuthenticatedFocusRoute
  '/goals': typeof AuthenticatedGoalsRoute
  '/habits': typeof AuthenticatedHabitsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/pricing': typeof AuthenticatedPricingRoute
  '/roadmaps': typeof AuthenticatedRoadmapsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/study': typeof AuthenticatedStudyRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/api/chat': typeof ApiChatRoute
  '/api/health': typeof ApiHealthRoute
  '/api/log-error': typeof ApiLogErrorRoute
  '/api/material-chat': typeof ApiMaterialChatRoute
  '/api/upload-document': typeof ApiUploadDocumentRoute
  '/conversation/$threadId': typeof AuthenticatedConversationThreadIdRoute
  '/lesson/$itemId': typeof AuthenticatedLessonItemIdRoute
  '/material/$resourceId': typeof AuthenticatedMaterialResourceIdRoute
  '/page/$pageId': typeof AuthenticatedPagePageIdRoute
  '/resource/$resourceId': typeof AuthenticatedResourceResourceIdRoute
  '/roadmap/$roadmapId': typeof AuthenticatedRoadmapRoadmapIdRoute
  '/api/webhooks/razorpay': typeof ApiWebhooksRazorpayRoute
  '/conversation': typeof AuthenticatedConversationIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/activity': typeof AuthenticatedActivityRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/documents': typeof AuthenticatedDocumentsRoute
  '/_authenticated/focus': typeof AuthenticatedFocusRoute
  '/_authenticated/goals': typeof AuthenticatedGoalsRoute
  '/_authenticated/habits': typeof AuthenticatedHabitsRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/pricing': typeof AuthenticatedPricingRoute
  '/_authenticated/roadmaps': typeof AuthenticatedRoadmapsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/study': typeof AuthenticatedStudyRoute
  '/_authenticated/tasks': typeof AuthenticatedTasksRoute
  '/api/chat': typeof ApiChatRoute
  '/api/health': typeof ApiHealthRoute
  '/api/log-error': typeof ApiLogErrorRoute
  '/api/material-chat': typeof ApiMaterialChatRoute
  '/api/upload-document': typeof ApiUploadDocumentRoute
  '/_authenticated/conversation/$threadId': typeof AuthenticatedConversationThreadIdRoute
  '/_authenticated/lesson/$itemId': typeof AuthenticatedLessonItemIdRoute
  '/_authenticated/material/$resourceId': typeof AuthenticatedMaterialResourceIdRoute
  '/_authenticated/page/$pageId': typeof AuthenticatedPagePageIdRoute
  '/_authenticated/resource/$resourceId': typeof AuthenticatedResourceResourceIdRoute
  '/_authenticated/roadmap/$roadmapId': typeof AuthenticatedRoadmapRoadmapIdRoute
  '/api/webhooks/razorpay': typeof ApiWebhooksRazorpayRoute
  '/_authenticated/conversation/': typeof AuthenticatedConversationIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/activity'
    | '/dashboard'
    | '/documents'
    | '/focus'
    | '/goals'
    | '/habits'
    | '/onboarding'
    | '/pricing'
    | '/roadmaps'
    | '/settings'
    | '/study'
    | '/tasks'
    | '/api/chat'
    | '/api/health'
    | '/api/log-error'
    | '/api/material-chat'
    | '/api/upload-document'
    | '/conversation/$threadId'
    | '/lesson/$itemId'
    | '/material/$resourceId'
    | '/page/$pageId'
    | '/resource/$resourceId'
    | '/roadmap/$roadmapId'
    | '/api/webhooks/razorpay'
    | '/conversation/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/activity'
    | '/dashboard'
    | '/documents'
    | '/focus'
    | '/goals'
    | '/habits'
    | '/onboarding'
    | '/pricing'
    | '/roadmaps'
    | '/settings'
    | '/study'
    | '/tasks'
    | '/api/chat'
    | '/api/health'
    | '/api/log-error'
    | '/api/material-chat'
    | '/api/upload-document'
    | '/conversation/$threadId'
    | '/lesson/$itemId'
    | '/material/$resourceId'
    | '/page/$pageId'
    | '/resource/$resourceId'
    | '/roadmap/$roadmapId'
    | '/api/webhooks/razorpay'
    | '/conversation'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/activity'
    | '/_authenticated/dashboard'
    | '/_authenticated/documents'
    | '/_authenticated/focus'
    | '/_authenticated/goals'
    | '/_authenticated/habits'
    | '/_authenticated/onboarding'
    | '/_authenticated/pricing'
    | '/_authenticated/roadmaps'
    | '/_authenticated/settings'
    | '/_authenticated/study'
    | '/_authenticated/tasks'
    | '/api/chat'
    | '/api/health'
    | '/api/log-error'
    | '/api/material-chat'
    | '/api/upload-document'
    | '/_authenticated/conversation/$threadId'
    | '/_authenticated/lesson/$itemId'
    | '/_authenticated/material/$resourceId'
    | '/_authenticated/page/$pageId'
    | '/_authenticated/resource/$resourceId'
    | '/_authenticated/roadmap/$roadmapId'
    | '/api/webhooks/razorpay'
    | '/_authenticated/conversation/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiLogErrorRoute: typeof ApiLogErrorRoute
  ApiMaterialChatRoute: typeof ApiMaterialChatRoute
  ApiUploadDocumentRoute: typeof ApiUploadDocumentRoute
  ApiWebhooksRazorpayRoute: typeof ApiWebhooksRazorpayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/activity': {
      id: '/_authenticated/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AuthenticatedActivityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents': {
      id: '/_authenticated/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthenticatedDocumentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/focus': {
      id: '/_authenticated/focus'
      path: '/focus'
      fullPath: '/focus'
      preLoaderRoute: typeof AuthenticatedFocusRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/goals': {
      id: '/_authenticated/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof AuthenticatedGoalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/habits': {
      id: '/_authenticated/habits'
      path: '/habits'
      fullPath: '/habits'
      preLoaderRoute: typeof AuthenticatedHabitsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pricing': {
      id: '/_authenticated/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof AuthenticatedPricingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/roadmaps': {
      id: '/_authenticated/roadmaps'
      path: '/roadmaps'
      fullPath: '/roadmaps'
      preLoaderRoute: typeof AuthenticatedRoadmapsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/study': {
      id: '/_authenticated/study'
      path: '/study'
      fullPath: '/study'
      preLoaderRoute: typeof AuthenticatedStudyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks': {
      id: '/_authenticated/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/log-error': {
      id: '/api/log-error'
      path: '/api/log-error'
      fullPath: '/api/log-error'
      preLoaderRoute: typeof ApiLogErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/material-chat': {
      id: '/api/material-chat'
      path: '/api/material-chat'
      fullPath: '/api/material-chat'
      preLoaderRoute: typeof ApiMaterialChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload-document': {
      id: '/api/upload-document'
      path: '/api/upload-document'
      fullPath: '/api/upload-document'
      preLoaderRoute: typeof ApiUploadDocumentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/conversation/': {
      id: '/_authenticated/conversation/'
      path: '/conversation'
      fullPath: '/conversation/'
      preLoaderRoute: typeof AuthenticatedConversationIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conversation/$threadId': {
      id: '/_authenticated/conversation/$threadId'
      path: '/conversation/$threadId'
      fullPath: '/conversation/$threadId'
      preLoaderRoute: typeof AuthenticatedConversationThreadIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lesson/$itemId': {
      id: '/_authenticated/lesson/$itemId'
      path: '/lesson/$itemId'
      fullPath: '/lesson/$itemId'
      preLoaderRoute: typeof AuthenticatedLessonItemIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/material/$resourceId': {
      id: '/_authenticated/material/$resourceId'
      path: '/material/$resourceId'
      fullPath: '/material/$resourceId'
      preLoaderRoute: typeof AuthenticatedMaterialResourceIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/page/$pageId': {
      id: '/_authenticated/page/$pageId'
      path: '/page/$pageId'
      fullPath: '/page/$pageId'
      preLoaderRoute: typeof AuthenticatedPagePageIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/resource/$resourceId': {
      id: '/_authenticated/resource/$resourceId'
      path: '/resource/$resourceId'
      fullPath: '/resource/$resourceId'
      preLoaderRoute: typeof AuthenticatedResourceResourceIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/roadmap/$roadmapId': {
      id: '/_authenticated/roadmap/$roadmapId'
      path: '/roadmap/$roadmapId'
      fullPath: '/roadmap/$roadmapId'
      preLoaderRoute: typeof AuthenticatedRoadmapRoadmapIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/webhooks/razorpay': {
      id: '/api/webhooks/razorpay'
      path: '/api/webhooks/razorpay'
      fullPath: '/api/webhooks/razorpay'
      preLoaderRoute: typeof ApiWebhooksRazorpayRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedActivityRoute: typeof AuthenticatedActivityRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDocumentsRoute: typeof AuthenticatedDocumentsRoute
  AuthenticatedFocusRoute: typeof AuthenticatedFocusRoute
  AuthenticatedGoalsRoute: typeof AuthenticatedGoalsRoute
  AuthenticatedHabitsRoute: typeof AuthenticatedHabitsRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedPricingRoute: typeof AuthenticatedPricingRoute
  AuthenticatedRoadmapsRoute: typeof AuthenticatedRoadmapsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedStudyRoute: typeof AuthenticatedStudyRoute
  AuthenticatedTasksRoute: typeof AuthenticatedTasksRoute
  AuthenticatedConversationThreadIdRoute: typeof AuthenticatedConversationThreadIdRoute
  AuthenticatedLessonItemIdRoute: typeof AuthenticatedLessonItemIdRoute
  AuthenticatedMaterialResourceIdRoute: typeof AuthenticatedMaterialResourceIdRoute
  AuthenticatedPagePageIdRoute: typeof AuthenticatedPagePageIdRoute
  AuthenticatedResourceResourceIdRoute: typeof AuthenticatedResourceResourceIdRoute
  AuthenticatedRoadmapRoadmapIdRoute: typeof AuthenticatedRoadmapRoadmapIdRoute
  AuthenticatedConversationIndexRoute: typeof AuthenticatedConversationIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedActivityRoute: AuthenticatedActivityRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDocumentsRoute: AuthenticatedDocumentsRoute,
  AuthenticatedFocusRoute: AuthenticatedFocusRoute,
  AuthenticatedGoalsRoute: AuthenticatedGoalsRoute,
  AuthenticatedHabitsRoute: AuthenticatedHabitsRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedPricingRoute: AuthenticatedPricingRoute,
  AuthenticatedRoadmapsRoute: AuthenticatedRoadmapsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedStudyRoute: AuthenticatedStudyRoute,
  AuthenticatedTasksRoute: AuthenticatedTasksRoute,
  AuthenticatedConversationThreadIdRoute:
    AuthenticatedConversationThreadIdRoute,
  AuthenticatedLessonItemIdRoute: AuthenticatedLessonItemIdRoute,
  AuthenticatedMaterialResourceIdRoute: AuthenticatedMaterialResourceIdRoute,
  AuthenticatedPagePageIdRoute: AuthenticatedPagePageIdRoute,
  AuthenticatedResourceResourceIdRoute: AuthenticatedResourceResourceIdRoute,
  AuthenticatedRoadmapRoadmapIdRoute: AuthenticatedRoadmapRoadmapIdRoute,
  AuthenticatedConversationIndexRoute: AuthenticatedConversationIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiChatRoute: ApiChatRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiLogErrorRoute: ApiLogErrorRoute,
  ApiMaterialChatRoute: ApiMaterialChatRoute,
  ApiUploadDocumentRoute: ApiUploadDocumentRoute,
  ApiWebhooksRazorpayRoute: ApiWebhooksRazorpayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
